const html_ = m("html")

const head_ = m("head")
const title_ = m("title")
const meta_ = m("meta")

# sections https://html.spec.whatwg.org/#sections
const body_  = m("body")
const article_ = m("article")
const section_ = m("section")
const nav_ = m("nav")
const aside_ = m("aside")
const h1_ = m("h1")
const h2_ = m("h2")
const h3_ = m("h3")
const h4_ = m("h4")
const h5_ = m("h5")
const h6_ = m("h6")
const hgroup_ = m("hgroup")
const header_ = m("header")
const footer_ = m("footer")
const address_ = m("address")

# grouping https://html.spec.whatwg.org/#grouping-content
const p_ = m("p")
const hr_ = m("hr")
const pre_ = m("pre")
const blockquote_ = m("blockquote")
const ol_ = m("ol")
const ul_ = m("ul")
const menu_ = m("menu")
const li_ = m("li")
const dl_ = m("dl")
const dt_ = m("dt")
const dd_ = m("dd")
const figure_ = m("figure")
const figcaption_ = m("figcaption")
const main_ = m("main")
const div_ = m("div")

# text level https://html.spec.whatwg.org/#text-level-semantics
const a_ = m("a")
const em_ = m("em")
const strong_ = m("strong")
const small_ = m("small")
const s_ = m("s")
const cite_ = m("cite")
const q_ = m("q")
const dfn_ = m("dfn")
const abbr_ = m("abbr")
const ruby_ = m("ruby")
const rt_ = m("rt")
const rp_ = m("rp")
const data_ = m("data")
const time_ = m("time")
const code_ = m("code")
const var_ = m("var")
const samp_ = m("samp")
const kbd_ = m("kbd")
const sub_ = m("sub")
const sup_ = m("sup")
const i_ = m("i")
const b_ = m("b")
const u_ = m("u")
const mark_ = m("mark")
const bdi_ = m("bdi")
const bdo_ = m("bdo")
const span_ = m("span")
const br_ = m("br")
const wbr_ = m("wbr")

# link types
const a_alternate_ = a_(rel="alternate")
const a_author_ = a_(rel="author")
const a_bookmark_ = a_(rel="bookmark")
const a_canonical_ = a_(rel="canonical")
const a_dnsprefetch_ = a_(rel="dns-prefetch")
const a_external_ = a_(rel="external")
const a_help_ = a_(rel="help")
const a_icon_ = a_(rel="icon")
const a_license_ = a_(rel="license")
const a_modulepreupload_ = a_(rel="modulepreupload")
const a_nofollow_ = a_(rel="nofollow")
const a_noopener_ = a_(rel="noopener")
const a_noreferrer_ = a_(rel="noreferrer")
const a_opener_ = a_(rel="opener")
const a_pingback_ = a_(rel="pingback")
const a_preconnect_ = a_(rel="preconnect")
const a_prefetch_ = a_(rel="prefetch")
const a_preload_ = a_(rel="preload")
const a_prerender_ = a_(rel="prerender")
const a_search_ = a_(rel="search")
const a_stylesheet_ = a_(rel="stylesheet")
const a_tag_ = a_(rel="tag")
const a_next_ = a_(rel="next")
const a_prev_ = a_(rel="prev")

# area https://html.spec.whatwg.org/#the-area-element
const area_ = m("area")
const area_circle = area_(shape="circle")
const area_rectangle = area_(shape="rect")
const area_polygon = area_(shape_="poly")
